class ResumeKegawatdaruratanMapper {
  static Map<String, dynamic> map(Map<String, dynamic> formData) {
    return {
      'identitas': {
        'nama_lengkap': formData['nama_lengkap'],
        'umur': formData['umur'],
        'jenis_kelamin': formData['jenis_kelamin'],
        'alamat': formData['alamat'],
        'tanggal_masuk': formData['tanggal_masuk'],
      },
      'riwayat_keluhan': {
        'keluhan_utama': formData['keluhan_utama'],
        'riwayat_penyakit_sekarang': formData['riwayat_penyakit_sekarang'],
        'faktor_pencetus': formData['faktor_pencetus'],
      },
      'pemeriksaan_fisik': {
        'keadaan_umum': formData['keadaan_umum'],
        'tanda_vital': formData['tanda_vital'],
        'pemeriksaan_lain': formData['pemeriksaan_lain'],
      },
      'status_mental': {
        'kesadaran': formData['kesadaran'],
        'orientasi': formData['orientasi'],
        'bentuk_pemikiran': formData['bentuk_pemikiran'],
        'isi_pemikiran': formData['isi_pemikiran'],
        'persepsi': formData['persepsi'],
      },
      'diagnosis': {
        'diagnosis_utama': formData['diagnosis_utama'],
        'diagnosis_banding': formData['diagnosis_banding'],
        'diagnosis_tambahan': formData['diagnosis_tambahan'],
      },
      'tindakan': {
        'tindakan_medis': formData['tindakan_medis'],
        'tindakan_keperawatan': formData['tindakan_keperawatan'],
        'terapi_psikososial': formData['terapi_psikososial'],
      },
      'implementasi': {
        'pelaksanaan_intervensi': formData['pelaksanaan_intervensi'],
        'kolaborasi_tim': formData['kolaborasi_tim'],
        'edukasi': formData['edukasi'],
      },
      'evaluasi': {
        'respon_intervensi': formData['respon_intervensi'],
        'perubahan_klinis': formData['perubahan_klinis'],
        'tujuan_tercapai': formData['tujuan_tercapai'],
        'hambatan_perawatan': formData['hambatan_perawatan'],
      },
      'rencana_lanjut': {
        'rencana_medis': formData['rencana_medis'],
        'rencana_keperawatan': formData['rencana_keperawatan'],
        'rencana_pemantauan': formData['rencana_pemantauan'],
      },
      'rencana_keluarga': {
        'keterlibatan_keluarga': formData['keterlibatan_keluarga'],
        'edukasi_keluarga': formData['edukasi_keluarga'],
        'dukungan_keluarga': formData['dukungan_keluarga'],
      },
      'renpra': formData['diagnosis'] != null
          ? {
              'diagnosis': formData['diagnosis'],
              'intervensi': formData['intervensi'],
              'tujuan': formData['tujuan'],
              'kriteria': formData['kriteria'],
              'rasional': formData['rasional'],
              'evaluasi': formData['evaluasi_renpra'],
            }
          : null,
      // flat mirror for BE compatibility
      'nama_lengkap': formData['nama_lengkap'],
      'umur': formData['umur'],
      'jenis_kelamin': formData['jenis_kelamin'],
      'alamat': formData['alamat'],
      'tanggal_masuk': formData['tanggal_masuk'],
      'keluhan_utama': formData['keluhan_utama'],
      'riwayat_penyakit_sekarang': formData['riwayat_penyakit_sekarang'],
      'faktor_pencetus': formData['faktor_pencetus'],
      'keadaan_umum': formData['keadaan_umum'],
      'tanda_vital': formData['tanda_vital'],
      'pemeriksaan_lain': formData['pemeriksaan_lain'],
      'kesadaran': formData['kesadaran'],
      'orientasi': formData['orientasi'],
      'bentuk_pemikiran': formData['bentuk_pemikiran'],
      'isi_pemikiran': formData['isi_pemikiran'],
      'persepsi': formData['persepsi'],
      'diagnosis_utama': formData['diagnosis_utama'],
      'diagnosis_banding': formData['diagnosis_banding'],
      'diagnosis_tambahan': formData['diagnosis_tambahan'],
      'tindakan_medis': formData['tindakan_medis'],
      'tindakan_keperawatan': formData['tindakan_keperawatan'],
      'terapi_psikososial': formData['terapi_psikososial'],
      'pelaksanaan_intervensi': formData['pelaksanaan_intervensi'],
      'kolaborasi_tim': formData['kolaborasi_tim'],
      'edukasi': formData['edukasi'],
      'respon_intervensi': formData['respon_intervensi'],
      'perubahan_klinis': formData['perubahan_klinis'],
      'tujuan_tercapai': formData['tujuan_tercapai'],
      'hambatan_perawatan': formData['hambatan_perawatan'],
      'rencana_medis': formData['rencana_medis'],
      'rencana_keperawatan': formData['rencana_keperawatan'],
      'rencana_pemantauan': formData['rencana_pemantauan'],
      'keterlibatan_keluarga': formData['keterlibatan_keluarga'],
      'edukasi_keluarga': formData['edukasi_keluarga'],
      'dukungan_keluarga': formData['dukungan_keluarga'],
      'renpra_diagnosis': formData['diagnosis'],
      'renpra_intervensi': formData['intervensi'],
      'renpra_tujuan': formData['tujuan'],
      'renpra_kriteria': formData['kriteria'],
      'renpra_rasional': formData['rasional'],
      'renpra_evaluasi': formData['evaluasi_renpra'],
    };
  }
}
